### ISSUE TITLE
Error fetching data - TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by frodef** [remuslazar/homeassistant-carwings#19]
## System Information

version | core-2024.8.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/Oslo
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1390
Downloaded Repositories | 23

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 234.3 GB
disk_used | 12.8 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | InfluxDB (5.0.0), SQLite Web (4.2.0), SSH Tunnel & Forwarding (1.2.1), Terminal & SSH (9.14.0), Tailscale (0.21.0), ESPHome (2024.7.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 9
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 8 August 2024 at 22:57
-- | --
current_recorder_run | 15 August 2024 at 23:40
estimated_db_size | 690.09 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/remuslazar/homeassistant-nissan-carwings/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I installed this integration via HACS, and configured it. Initialization did not work, giving this message in the UI and in the log:

2024-08-15 23:40:39.369 ERROR (MainThread) [custom_components.nissan_carwings]  Error fetching data - TypeError: list indices must be integers or slices, not str

From a quick peek in the code, the error looked to come from the pycarwings3 library. I installed and ran pycarwings3 directly (outside of HA), and got the exact same error, with some more debug info (pasted below). It looks to me that the servers provide an empty BatteryStatusRecords, which trips up pycarwings3. 

I then tried the official Nissan EV app on my phone, which also seemed unable to receive any info. I'm guessing the Nissan servers are on one of their frequirent "holidays" for whatever reason. Hopefully when the Nissan servers get back up again, this error will also go away. In any case it would be nice if pycarwings and/or homeassistant-carwings would handle this situation more gracefully.

I am in the Europe region.

DEBUG:pycarwings3.pycarwings3:Response HTTP Status Code: 200
DEBUG:pycarwings3.pycarwings3:Response HTTP Response Body: {"status":200,"BatteryStatusRecords":[]}
Traceback (most recent call last):
  File "/home/frode/src/pycarwings3/examples/./get-leaf-info.py", line 101, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/frode/src/pycarwings3/examples/./get-leaf-info.py", line 81, in main
    leaf_info = await leaf.get_latest_battery_status()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frode/.local/lib/python3.12/site-packages/pycarwings3/pycarwings3.py", line 498, in get_latest_battery_status
    return CarwingsLatestBatteryStatusResponse(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frode/.local/lib/python3.12/site-packages/pycarwings3/responses.py", line 675, in __init__
    bs = recs["BatteryStatus"]
         ~~~~^^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str


### Reproduction steps

1. Install via HACS
2. Configure in UI
3. Error appears in UI and logs, component never initializes.
...


### Debug logs

```text
2024-08-15 23:40:23.488 INFO (MainThread) [homeassistant.setup] Setting up nissan_carwings
2024-08-15 23:40:23.489 INFO (MainThread) [homeassistant.setup] Setup of domain nissan_carwings took 0.00 seconds
2024-08-15 23:40:23.489 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsDataUpdateCoordinator'> initialized with update in
terval 0:05:00
2024-08-15 23:40:23.778 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsClimateDataUpdateCoordinator'> initialized with up
date interval 0:05:00
2024-08-15 23:40:23.778 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsDrivingAnalysisDataUpdateCoordinator'> initialized
 with update interval 0:05:00
2024-08-15 23:40:23.778 INFO (MainThread) [custom_components.nissan_carwings] Starting Nissan Carwings integration for user=<me@email>

2024-08-15 23:40:39.369 ERROR (MainThread) [custom_components.nissan_carwings] FVF1 Error fetching data - TypeError: list indices must be integers or slices, not str
```


### Diagnostics dump

_No response_

**Comment by frodef** [comment]
As suspected, when the Nissan servers started behaving a few minutes ago now, the integration works fine it seems. It would still be good if this server (response) condition (which sadly be expected to be frequent) is dealt with better.

**Comment by frodef** [comment]
I am getting this same error again now (when it seems the Nissan servers are back on vacation for a few days).
