### ISSUE TITLE
[pycarwings3.pycarwings3] got an empty BatteryStatusRecords makes the integration fail (could be due to 2G shut down)

### ISSUE THREAD

**Issue by evest** [remuslazar/homeassistant-carwings#48]
## System Information

version | core-2024.9.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/Oslo
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4998
Installed Version | 1.34.0
Stage | running
Available Repositories | 1401
Downloaded Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 10, 2025 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-1.ui.nabu.casa
certificate_status | ready
instance_id | e26cf404b5804e879a0c2a083a0c5710
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.09.1
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 116.5 GB
disk_used | 13.8 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), TellStick (2.2.0), Samba share (12.3.2), Z-Wave JS (0.7.1), Advanced SSH & Web Terminal (19.0.0), deCONZ (7.0.0), Mosquitto broker (6.4.1), Zigbee2MQTT (1.40.1-1), Home Assistant Google Drive Backup (0.112.1), SQLite Web (4.2.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 11
-- | --
resources | 9
views | 20
mode | storage

</details>

<details><summary>Nibe Uplink Heat Pumps</summary>

api_endpoint_reachable | ok
-- | --

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 12, 2024 at 21:25
-- | --
current_recorder_run | September 13, 2024 at 11:34
estimated_db_size | 597.86 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/remuslazar/homeassistant-nissan-carwings/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Running version 0.2.1

When the integration is loading, it fails with the following error:
```
2024-09-13 13:47:11.324 INFO (MainThread) [custom_components.nissan_carwings] Starting Nissan Carwings integration for user=REDACTED
2024-09-13 13:47:17.698 DEBUG (MainThread) [custom_components.nissan_carwings] carwings3.get_leaf() OK: vin=REDACTED
2024-09-13 13:47:19.237 WARNING (MainThread) [pycarwings3.pycarwings3] got an empty BatteryStatusRecords
2024-09-13 13:47:19.237 DEBUG (MainThread) [custom_components.nissan_carwings] Finished fetching nissan_carwings data in 7.913 seconds (success: True)
2024-09-13 13:47:19.240 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity None for domain sensor with platform nissan_carwings
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 595, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 823, in _async_add_entity
    original_icon=entity.icon,
                  ^^^^^^^^^^^
  File "/config/custom_components/nissan_carwings/sensor.py", line 82, in icon
    charging = self.coordinator.data[DATA_BATTERY_STATUS_KEY].is_charging
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_charging'
```

I can authenticate using the app, and I can refresh/start the climate control, but I cannot see battery information in the app.

I then checked the online version on https://no.nissanconnect.eu/nb-no/CsmVehicle/Home/VIN-HERE. The battery information isn't showing there either.

However; when I logged in, I got this warning page (originally in Norwegian) :
https://www-nissan-no.translate.goog/carwings-maintenance.html?_x_tr_sl=no&_x_tr_tl=en&_x_tr_hl=no&_x_tr_pto=wapp

```
Dear customer,

We would like to inform you that the NissanConnect EV app currently connected to your car will be switched off in preparation for the 2G network shutdown. This will affect the Nissan LEAF produced until 2016 and the e-NV200 produced until 2018.

The discontinuation of the NissanConnect EV app is linked to the mobile network operators' decision to shut down the 2G network, which affects all car manufacturers that use the same 2G technology.

As a result, you will not be able to use your NissanConnect services remotely through the NissanConnect EV app from April 1, 2024.

However, we can inform you that the time setting of climate control and charging will still be available directly in the car's navigation system. 

We can assure you that Nissan will also continue its commitment in the future and invest in future-oriented technologies and platforms for future products.

Thank you for being a Nissan owner and for your support.

Sincerely,
Nissan
```

This might explain why it fails, but it seems that it might still be able to control the climate system, which is something at least. However, the integration needs to handle the missing battery data to get past the startup.

### Reproduction steps

Fails consistently when loading the integration.

### Debug logs

```text
2024-09-13 13:47:11.323 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsDataUpdateCoordinator'> initialized with update interval 0:05:00
2024-09-13 13:47:11.323 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsClimateDataUpdateCoordinator'> initialized with update interval 0:05:00
2024-09-13 13:47:11.324 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsDrivingAnalysisDataUpdateCoordinator'> initialized with update interval 0:05:00
2024-09-13 13:47:11.324 INFO (MainThread) [custom_components.nissan_carwings] Starting Nissan Carwings integration for user=REDACTED
2024-09-13 13:47:17.698 DEBUG (MainThread) [custom_components.nissan_carwings] carwings3.get_leaf() OK: vin=REDACTED
2024-09-13 13:47:19.237 WARNING (MainThread) [pycarwings3.pycarwings3] got an empty BatteryStatusRecords
2024-09-13 13:47:19.237 DEBUG (MainThread) [custom_components.nissan_carwings] Finished fetching nissan_carwings data in 7.913 seconds (success: True)
2024-09-13 13:47:19.240 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity None for domain sensor with platform nissan_carwings
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 595, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 823, in _async_add_entity
    original_icon=entity.icon,
                  ^^^^^^^^^^^
  File "/config/custom_components/nissan_carwings/sensor.py", line 82, in icon
    charging = self.coordinator.data[DATA_BATTERY_STATUS_KEY].is_charging
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_charging'
2024-09-13 13:47:19.254 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entity binary_sensor.leaf1stev_plug_status_2 for domain binary_sensor with platform nissan_carwings
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 595, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in __async_calculate_state
    available = self.available  # only call self.available once per update cycle
                ^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_carwings/binary_sensor.py", line 57, in available
    return self.coordinator.data[DATA_BATTERY_STATUS_KEY].is_connected is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_connected'
2024-09-13 13:47:19.260 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entity binary_sensor.leaf1stev_charging for domain binary_sensor with platform nissan_carwings
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 595, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in __async_calculate_state
    available = self.available  # only call self.available once per update cycle
                ^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_carwings/binary_sensor.py", line 83, in available
    return self.coordinator.data[DATA_BATTERY_STATUS_KEY].is_charging is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_charging'
2024-09-13 13:47:19.276 DEBUG (MainThread) [custom_components.nissan_carwings] carwings3.get_leaf() OK: vin=REDACTED
2024-09-13 13:47:19.279 DEBUG (MainThread) [custom_components.nissan_carwings] carwings3.get_leaf() OK: vin=REDACTED
2024-09-13 13:47:20.582 DEBUG (MainThread) [custom_components.nissan_carwings] carwings3.get_latest_hvac_status() OK: running=False, remaining_time=None, start/stop timestamp: None
2024-09-13 13:47:20.583 DEBUG (MainThread) [custom_components.nissan_carwings] Finished fetching nissan_carwings data in 1.307 seconds (success: True)
2024-09-13 13:47:21.157 ERROR (MainThread) [custom_components.nissan_carwings] Error fetching driving analysis data - KeyError: 'ElectricMileageLevel'
2024-09-13 13:47:21.158 ERROR (MainThread) [custom_components.nissan_carwings] Error fetching nissan_carwings data: Error fetching driving analysis data - KeyError: 'ElectricMileageLevel'
2024-09-13 13:47:21.158 DEBUG (MainThread) [custom_components.nissan_carwings] Finished fetching nissan_carwings data in 1.880 seconds (success: False)
```

**Comment by remuslazar** [comment]
The NissanConnectEV (Carwings) services seem to be down since 2 weeks or so.. Historically, I've seen the API go down for a few days, but this current outage appears to be more significant. I have attempted to contact Nissan for clarification or an update, but I haven't received any response yet.

The connectivity in the car is OK, the car can at least update the chargepoint data successfully. Let's hope that they will not really shut down the service altogether..

**Comment by Chaoscontrol** [comment]
Sorry if it's not completely related. Didn't the Carwings service become completely discontinued earlier this year (Feb or so)? [Source here. ](https://www.speakev.com/posts/3664698/)

I think you're mixing NissanConnect (which is the post early-2016 system and still usable even if server issues a few weeks ago) with Carwings (pre 2016, the one I have in the car and can't log in at all).

**Comment by remuslazar** [comment]
The service is now officially  called "NissanConnectEV" but still uses the legacy carwings API, also the official NissanConnectEV App from Nissan uses this API. This was also the reason why I have decided to use this name for the project (carwings), to distinguish it from [this integration](https://github.com/dan-r/HomeAssistant-NissanConnect), which works for Nissan vehicles 2016+ (see README). This integration uses the "new" NissanConnectAPI which unfortunately does not work for vehicles <=2016 (e.g. Nissan Leafs 30kWh)

The carwings API (the one being used by this project) was working till sep. 3 or so, my Nissan Leaf can also download data via cellular without issues.

**Comment by Chaoscontrol** [comment]
> The service is now officially called "NissanConnectEV" but still uses the legacy carwings API, also the official NissanConnectEV App from Nissan uses this API. This was also the reason why I have decided to use this name for the project (carwings), to distinguish it from [this integration](https://github.com/dan-r/HomeAssistant-NissanConnect), which works for Nissan vehicles 2016+ (see README). This integration uses the "new" NissanConnectAPI which unfortunately does not work for vehicles <=2016 (e.g. Nissan Leafs 30kWh)
> 
> The carwings API (the one being used by this project) was working till sep. 3 or so, my Nissan Leaf can also download data via cellular without issues.

Sorry, still a bit confused. 

So is the CarwingsAPI the one <=2016 vehicles use? 

> This integration uses the "new" NissanConnectAPI which unfortunately does not work for vehicles <=2016 (e.g. Nissan Leafs 30kWh)

When you say "this integration", you mean the [NissanConnect ](https://github.com/dan-r/HomeAssistant-NissanConnect) one? Or yours?

Still trying to figure out if yours should work on my 2015 Leaf. 

Thanks.

**Comment by remuslazar** [comment]
@Chaoscontrol

I mean, the [NissanConnect](https://github.com/dan-r/HomeAssistant-NissanConnect) integration uses the new API which is unfortunately not usable for vehicles <=2016. My integration uses the old, legacy "carwings" API for vehicles <=2016.

Currently there is an API outage since 2-3 weeks for now but we're locking forward that they will fix that.. This integration should work with your 2015 leaf as well, but, as I said, currently the API is down for some unknown reason. 

sorry for the confusion :)

**Comment by Chaoscontrol** [comment]
> @Chaoscontrol
> 
> I mean, the [NissanConnect](https://github.com/dan-r/HomeAssistant-NissanConnect) integration uses the new API which is unfortunately not usable for vehicles <=2016. My integration uses the old, legacy "carwings" API for vehicles <=2016.
> 
> Currently there is an API outage since 2-3 weeks for now but we're locking forward that they will fix that.. This integration should work with your 2015 leaf as well, but, as I said, currently the API is down for some unknown reason.
> 
> sorry for the confusion :)

WOW! Amazing then. I really find it weird as all other reports I've seen claim the disconnection of the service. 

Apart from the last weeks outage, how should this be connected? Where can I get those details? And I guess I should enter them into the car head unit?

**Comment by remuslazar** [comment]
@Chaoscontrol you should make sure that you car does work with the current compatible Nissan Official App (for Apple e.g. https://apps.apple.com/de/app/nissanconnect-ev/id407497029). This will require to setup an account here http://www.nissanconnect.eu, enter you VIN, wait for the approval and then you can use the credentials for the app. It this all works and the API outage has been fixed, you can also use the credentials to setup this integration.

Currently also the Nissan+YOU service seems to be buggy and unavailable, though.. you could try to contact Nissan for support..

**Comment by Chaoscontrol** [comment]
@remuslazar I think I was in the right. Maybe this is being discontinued differently in different countries? 

[The Official Nissan app on Android](https://play.google.com/store/apps/details?id=com.digitas.android.nissan.carwings) clearly says it's only compatible with Leaf after Nov 2015. 

I'm in the UK, and [this is what the NissanConnect page shows](https://www.nissan.co.uk/carwings-maintenance.html). This is what I had read elsewhere. 

I did create an account on Nissan+YOU, added my VIN and it added my car instantly. I just haven't been able to log in inside the car itself to Carwings.

**Comment by remuslazar** [comment]
🎉 **Good news**! It seems that Nissan has recently resolved the API issues. The current release now also handles cases where the API is down, by reporting the sensors with an "unknown" value rather than marking all sensors as unavailable.

Everything should be working correctly now, so I will go ahead and close this issue as it has been resolved in the latest release, as previously mentioned.

**Comment by Chaoscontrol** [comment]
@remuslazar 

I get authentication error. But I can log with the same details on Nissan+YOU website. Any idea? 

What are your thoughts on my last comment about the UK Nissan official note? What country are you testing in?

**Comment by remuslazar** [comment]
@Chaoscontrol I am from Germany, at least here everything is working again since a couple of hours.

First, make sure that you are able to fetch the battery status and all that using the official working NissanConnectApp. I have only apple devices, no clue which Android version is currently compatible with your Leaf, sorry. If this all works, you can try to use the credentials to setup the integration. The integration will check if the battery status is being available after login, if this fails an error will be thrown.

**Comment by Chaoscontrol** [comment]
@remuslazar I have strong suspicion that it might only be working in Germany or some other countries. 

It's true that the Deutsch website doesn't show the Nissan notice. UK and Spain do. France doesn't either. 

I have tried logging in the Nissan Connect EV app on Android and it fails to log in as well. If I try in the car itself it will probably fail as well (will try at some point).

**Comment by remuslazar** [comment]
@Chaoscontrol probably. btw: you can not use the credentials to log in using the car head unit. You can just use the VIN to register the car and to bind the car to your account, which will also require some kind of approval from Nissan. At least here in Germany did it work that way.

**Comment by Chaoscontrol** [comment]
Ah ok that's worth knowing at least. Will save me from trying with the crappy Carwings UI in the car. 

I did add the VIN as I said, but in my case it did not require any authorisation at all. It was all instant.
